version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - echo region AWS_DEFAULT_REGION id AWS_ACCOUNT_ID
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 550762782574.dkr.ecr.us-east-1.amazonaws.com
      - echo Logging Success
  build:
    commands:
      - echo Building Docker image...
      - cd analytics
      - docker build -t hoand33-ecr .
      - docker tag hoand33-ecr:latest 550762782574.dkr.ecr.us-east-1.amazonaws.com/hoand33-ecr:CODEBUILD_BUILD_NUMBER
      - echo build Success
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push 550762782574.dkr.ecr.us-east-1.amazonaws.com/hoand33-ecr:CODEBUILD_BUILD_NUMBER
      - echo push Success
