apiVersion: v1
kind: ConfigMap
metadata:
  name: pro-properties
data:
  DB_NAME: "hoanddb"
  DB_USER: "hoand"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-pro-properties
type: Opaque
data:
  DB_PASSWORD: aG9hbmQ=
